### ISSUE TITLE
forge.sparql(): Allow `LIMIT` on the query itself

### ISSUE THREAD

**Issue by annakristinkaufmann** [BlueBrain/nexus-forge#189]
When using `forge.sparql()`, one cannot provide the `LIMIT` in the query string itself without setting the `limit` argument on the method to `None`.

While this throws a `HTTPError: 400 Client Error: Bad Request for url: https://***defaultSparqlIndex/sparql and QueryingError: 400 Client Error: Bad Request for url: https://***defaultSparqlIndex/sparql` error:

- `forge.sparql("SELECT ?s ?p ?o WHERE {?s ?p ?o} LIMIT 20")`

the following work:
- `forge.sparql("SELECT ?s ?p ?o WHERE {?s ?p ?o}", limit=20)`
- `forge.sparql("SELECT ?s ?p ?o WHERE {?s ?p ?o} LIMIT 20", limit=None)`

A user should be allowed to provide the `LIMIT` in the query string itself without having to set the `limit` argument to `None`

The limit default value is set here:
- https://github.com/BlueBrain/nexus-forge/blob/a65d4e37e6b30f3261c5914fb1e536720b41dd00/kgforge/core/forge.py#L347

The query string is being built here: 
- https://github.com/BlueBrain/nexus-forge/blob/9287baa6338876fd0e61624f97e21e2d6679b274/kgforge/specializations/stores/bluebrain_nexus.py#L453

**Comment by tobiasschweizer** [comment]
Would it be possible to improve the error message too? I assume that the reason for the rejection is invalid SPARQL (`None` maybe ends up in the query string).
