### ISSUE TITLE
forge.from_jsonld(): Handling Types of Literal Values in JSON-LD

### ISSUE THREAD

**Issue by tobiasschweizer** [BlueBrain/nexus-forge#194]
Hi there

I have a problem regarding types of literal values in JSON-LD.

Example:

data:
```python
grant = {
  "@context": {
    "@vocab": "http://schema.org/",
    "xsd": "http://www.w3.org/2001/XMLSchema#"
  },
  "@type": "Grant",
  "name": "My grant",
  "description": "My first granted grant",
  "startDate": {
      "@type": "xsd:date",
      "@value": "2021-09-23Z"
    }
}
```

schema file with shape
```json
{
  "@context": [
    "https://incf.github.io/neuroshapes/contexts/schema.json",
    {
      "this": "https://schemaorgshapes.org/dash/grant/shapes/"
    }
  ],
  "@type": "nxv:Schema",
  "@id": "https://schemaorgshapes.org/dash/grant",
  "imports": [],
  "shapes": [
    {
      "@id": "this:GrantShape",
      "@type": "sh:NodeShape",
      "label": "A grant",
      "targetClass": "schema:Grant",
      "property": [
        {
          "path": "schema:name",
          "name": "Name",
          "description": "The Grant name.",
          "datatype": "xsd:string",
          "minCount": 1,
          "maxCount": 1
        },
        {
          "path": "schema:description",
          "name": "Description",
          "description": "The Grant description",
          "datatype": "xsd:string",
          "minCount": 1,
          "maxCount": 1
        },
        {
          "path": "schema:startDate",
          "name": "Start Date",
          "description": "The Grant's start date",
          "minCount": 1,
          "maxCount": 1,
          "datatype": "xsd:date"
        }
      ]
    }
  ]
}
```

When doing the following, I get a validation error:

```python

res = forge.from_jsonld(grant)

forge.validate(res)
```

> Constraint Violation in DatatypeConstraintComponent (http://www.w3.org/ns/shacl#DatatypeConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:datatype xsd:date ; sh:description Literal("The Grant's start date") ; sh:maxCount Literal("1", datatype=xsd:integer) ; sh:minCount Literal("1", datatype=xsd:integer) ; sh:name Literal("Start Date") ; sh:path schema:startDate ]
	Focus Node: [  <http://schema.org/description> Literal("My first granted grant") ; <http://schema.org/name> Literal("My grant") ; <http://schema.org/startDate> [ <http://schema.org/value> Literal("2021-09-23Z") ; rdf:type xsd:date ] ; rdf:type <http://schema.org/Grant> ]
	Value Node: [ <http://schema.org/value> Literal("2021-09-23Z") ; rdf:type xsd:date ]
	Result Path: schema:startDate

To me, the encoding of the `xsd:date` seems correct in JSON-LD, see also [here](https://json-ld.org/spec/latest/json-ld/#typed-values).

However , the message for the focus node looks a bit strange:

> Value Node: [ <http://schema.org/value> Literal("2021-09-23Z") ; rdf:type xsd:date ]

Could it be that the `@value` is mistaken for the schema.org property <http://schema.org/value>?

I'd be grateful for any help. Thanks a lot.

**Comment by tobiasschweizer** [comment]
maybe this shouldn't happen for `@value`:

https://github.com/BlueBrain/nexus-forge/blob/72c871164c1cac06c08b732ceeec0a0644e99edf/kgforge/core/conversions/rdf.py#L397-L398

**Comment by MFSY** [comment]
@tobiasschweizer can you try again with master branch to see if the issue is fixed ?

**Comment by tobiasschweizer** [comment]
@MFSY Sure Thing! I'll try this tomorrow morning.
Could you instruct me how to build the library from source? I'd prefer to use a venv.

**Comment by MFSY** [comment]
Some info are available in the[ install doc](https://nexus-forge.readthedocs.io/en/latest/index.html#installation):

A simple:

`pip install git+https://github.com/BlueBrain/nexus-forge
`
Should be enough.

**Comment by tobiasschweizer** [comment]
@MFSY I installed nexus-forge from master and it works now as expected. Thanks a lot for fixing this! Will there be a minor release with this fix?

I still get some (debug) output from `forge.from_jsonld()`:

> @type
@type
@type
@type

**Comment by MFSY** [comment]
Great this work. Nice catch for the print issue.
