### ISSUE TITLE
schema_id not taken into account for bulk update of resources

### ISSUE THREAD

**Issue by annakristinkaufmann** [BlueBrain/nexus-forge#256]
For the Nexus store specialization, a specified `schema_id` is currently not taken into account when using `forge.update()` on a list of resources (`def _update_many`) while it is being considered when using `forge.update()` on an individual resource (`def _update_one`). See related issue on Nexus Delta: https://github.com/BlueBrain/nexus/issues/3401

**Comment by ssssarah** [comment]
This is no longer true, this can be closed @MFSY
