### ISSUE TITLE
MyBinder notebook error

### ISSUE THREAD

**Issue by stefanoantonel** [BlueBrain/nexus-forge#268]
When I try to open the mybinder link on https://nexus-forge.readthedocs.io/en/latest/#getting-started
I see:
```
Invalid build token
```

I'm not able to run the notebook

**Comment by MFSY** [comment]
I just tried and it worked. May Binder was having issue for some minutes. Can you try again and let us know ?

**Comment by stefanoantonel** [comment]
Great then! it is working again! Thank you
