### ISSUE TITLE
Retrieve a resource by _self

### ISSUE THREAD

**Issue by MFSY** [BlueBrain/nexus-forge#270]
Currently forge.retrieve(id=resource.id) only accepts resource.id when using BlueBrainNexus. Under the hood forge is building a Nexus address for the requested URI by concatenating the endpoint, the org, the proj, the schema and then the URI. A resource._store_metadata._self is already made of the endpoint, the org, the proj, the schema and then the URI.

forge.retrieve(id=resource._store_metadata._self) should work

**Comment by ssssarah** [comment]
Can we close this?
