### ISSUE TITLE
EXACT_CASEINSENSITIVE_MATCH not resolving

### ISSUE THREAD

**Issue by lecriste** [BlueBrain/nexus-forge#276]
The EXACT_MATCH strategy is resolving a label that EXACT_CASEINSENSITIVE_MATCH is not:
```
forge.resolve("PV+", scope="ontology", target="terms", strategy="EXACT_MATCH")
Resource(_last_action=None, _validated=False, _synchronized=False, _store_metadata=None, id='https://bbp.epfl.ch/ontologies/core/bmo/PV+', type=['NeuronMolecularType', 'Class'], label='PV+', _inner_sync=False, isDefinedBy='https://bbp.epfl.ch/ontologies/core/bmo', subClassOf='bmo:NeuronMolecularType')

forge.resolve("PV+", scope="ontology", target="terms", strategy="EXACT_CASEINSENSITIVE_MATCH")

```

**Comment by crisely09** [comment]
There is a problem with special characters, I have an idea, I will try to fix it this week.

**Comment by lecriste** [comment]
I found two cases in which the returned resource is not the expected one:

1. 'Mc' is resolved to [Olfactory Bulb Main Mitral Cell](https://bbp.epfl.ch/nexus/web/neurosciencegraph/datamodels/resources/http%3A%2F%2Furi.interlex.org%2Fbase%2Filx_0107933) instead of [Neocortex Martinotti Cell](https://bbp.epfl.ch/nexus/web/neurosciencegraph/datamodels/resources/http%3A%2F%2Furi.interlex.org%2Fbase%2Filx_0107375)
2. 'Bac' is resolved to [Mesh of Bed nucleus of the anterior commissure](https://bbp.epfl.ch/nexus/web/bbp/atlas/resources/https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2F573c0099-1d3e-4c4d-beaf-30004a77c629) instead of [Burst accommodating electrical type](https://bbp.epfl.ch/nexus/web/neurosciencegraph/datamodels/resources/http%3A%2F%2Furi.interlex.org%2Fbase%2Filx_0738199)

As we discussed in person, we may want to apply a resolving priority among `label`, `prefLabel`, `altLabel`, `notation`, ...

The 'Mc' issue is probably due to a swap between `label` and `altLabel` in the registered resource.

**Comment by MFSY** [comment]
Hi here. Is this resolved ?
