### ISSUE TITLE
Retrieving elastic search view: mapping containing @id field breaks

### ISSUE THREAD

**Issue by ssssarah** [BlueBrain/nexus-forge#299]
When retrieving elastic search views, the content of the object may include mappings containing "@id" fields ("@id" as a key, and the associated value as a dict). 
This fails in the following file: [https://github.com/BlueBrain/nexus-forge/blob/master/kgforge/core/conversions/rdf.py](https://github.com/BlueBrain/nexus-forge/blob/master/kgforge/core/conversions/rdf.py)
In line 467, the condition that the key should be equal to "@id" is passed when it shouldn't in this particular case, because the value associated to the key does not contain an id string, but an object, so context.resolve fails (applies a string operation on a dictionary). 
I haven't looked at further at which if case it should be treated under (maybe the case that handles dicts)

**Comment by crisely09** [comment]
@ssssarah  could you provide an example query?
