### ISSUE TITLE
Configuration paths from getting started notebooks are outdated

### ISSUE THREAD

**Issue by ssssarah** [BlueBrain/nexus-forge#345]
There are no longer configurations directly available at `./examples/configurations`
(relatively to the `./examples/notebooks/getting_started` notebooks: `../../configurations`).

I'm not sure which of the many configs it should be though. 
`[...]/demo-store/demo-config-with-resolvers.yml` ? @crisely09 

There will be other errors later down the notebook using the demo store (due to some operations being unavailable in that store)

**Comment by crisely09** [comment]
As discussed on slack, all the notebooks in the `getting_started` folder depend on the configuration file created with the `00 - Initialization` notebook, which uses the sandbox deployment of BlueBrainNexus store. One could think of adding other example notebooks that don't use this store as default. That said, I will close this issue, feel free to create a new one to request for more general example notebooks as an enhancement.
