### ISSUE TITLE
Missing forge method to add images to resources

### ISSUE THREAD

**Issue by crisely09** [BlueBrain/nexus-forge#388]
Similar to `add_distribution` to the dataset objects, we should have a `add_image` for Resources.
This would be very useful, for example for traces, but now E-Models will also have images (to be used for thumbnails), and maybe other model entities would require the same.

**Comment by MFSY** [comment]
Can this be closed @crisely09 ?

**Comment by crisely09** [comment]
Yes, this can be closed.
