### ISSUE TITLE
Install required version of Pyshacl when installing Nexus Forge

### ISSUE THREAD

**Issue by annakristinkaufmann** [BlueBrain/nexus-forge#43]
The `Shape' object has no attribute 'traverse'` error described here: #36 is due to the installed version of `Pyshacl`. On 2020-07-10, a new version of `Pyshacl` was released on PyPi and `Nexus Forge` does not specify a particular `Pyshacl` version for installation. I.e., when installing the Nexus Forge now, the latest release `Pyshacl 0.12.0` will be installed which causes the error. Running the same notebook as in #36  with `Pyshacl 0.11.6.post1` works fine.

**Comment by MFSY** [comment]
@annakristinkaufmann is this fixed for now ?

**Comment by annakristinkaufmann** [comment]
Yes!
