### ISSUE TITLE
Support for configurable SPARQL endpoint in the BlueBrain Nexus Delta Store when using forge.search

### ISSUE THREAD

**Issue by MFSY** [BlueBrain/nexus-forge#63]
When using BlueBrain Nexus Delta as a store, the [default SPARQL view](https://bluebrainnexus.io/docs/delta/api/current/views/sparql-view-api.html) is used without a possibility for the user to change and use another SPARQL endpoint.

I would be good to allow users to configure whatever SPARQL view they want to use as an endpoint for SPARQL queries.

**Comment by samuel-kerrien** [comment]
Thanks for the feedback @MFSY, can you give us more context and specifics of what you are trying to achieve ? Can you describe the type of configuration you would want for your new SPARQL view ?

**Comment by MFSY** [comment]
Hi,
Blue Brain Nexus Delta Sparql views are working just fine. This is an issue for the forge not to hard code the default sparql view of a given project but to enable users to configure them.
