### ISSUE TITLE
Implement instantiation of a Dataset from a Resource

### ISSUE THREAD

**Issue by annakristinkaufmann** [BlueBrain/nexus-forge#82]
Currently, there is no implementation to instantiate a **kgforge.specializations.resources.datasets.Dataset** type from an existing  **kgforge.core.resource.Resource** type.

Having this capability would be useful to e.g. retrieve a Resource from the store as Dataset allowing a user to benefit from methods available on the Dataset specialisation.

**Comment by MFSY** [comment]
Hi @annakristinkaufmann ,
The following code shows how to create a dataset object from a resource object. 

```python
from kgforge.specializations.resources import Dataset
forge = KnowledgeGraphForge("config.yml")
data = {
'id': 'https://kg.example.ch/associations/123',
 'type': 'Association',
 'agent': {'type': 'Person',
  'gender': {'id': 'http://purl.obolibrary.org/obo/PATO_0000383',
   'type': 'LabeledOntologyEntity',
   'label': 'female'},
  'name': 'Marie Curie'
 }
}

resource = forge.from_json(data)
dataset = Dataset(forge, **forge.as_json(resource))

forge.as_jsonld(dataset)
```

**Comment by annakristinkaufmann** [comment]
Hi @MFSY  ! Thanks a lot for this solution
